server:
  port: 8761

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${security.user.name}:${seciruty.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}